# Version
version: '3.4'

# Setup
services:

  # PHP
  php:
    depends_on:
      - db
    image: docker-php74
    restart: always
    ports:
      - 1212:80
    volumes:
      - ./myapplication:/var/www/html

  # PHPMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 2121:80
    environment:
      PMA_HOST: db

  # MySQL
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - my_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor

# Volumes
volumes:
  my_db: